[package]
name = "isolate-checker"
version = "0.1.0"
edition = "2021"

[dependencies]
swc_core = { version = "5.0.4", features = [ 
  "ecma_ast",
  "ecma_codegen",
  "ecma_parser",
  "ecma_quote",
  "common"
]}
miette = { version = "7.2.0", features = ["fancy"]}